version: '3'
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
    image: user_service:latest
    command: ./drogon_user_service --action=run-server  
