name: stage-build

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: echo "Run unit tests"  
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
    needs: test
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v4
    - name: Get latest tag from main branch
      id: get_latest_main_tag
      run: |
        git fetch origin main:refs/remotes/origin/main
        git checkout origin/main
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        git checkout origin/develop
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: Build Docker image
      run: |
        docker build \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --build-arg DB_HOST=${{ secrets.DB_HOST }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg DB_USER=${{ secrets.DB_USER }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -t user_service:${{ steps.tag_version.outputs.new_tag }} .
